# Generated by Django 4.2.23 on 2025-06-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.CharField(max_length=100, verbose_name='Director'),
        ),
    ]
