# Generated by Django 4.2.23 on 2025-06-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
    ]
