# Generated by Django 4.2.23 on 2025-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_request_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.TextField(verbose_name='nota'),
        ),
    ]
